#pragma once

#ifdef __APPLE__
/* #define KEYMOD_OPENAPPLE SDL_KMOD_LALT
#define KEYMOD_CLOSEDAPPLE SDL_KMOD_RALT */
#define KEYMOD_OPENAPPLE SDL_KMOD_LGUI
#define KEYMOD_CLOSEDAPPLE SDL_KMOD_RGUI
#define KEY_RESET SDLK_F10
#elif defined(linux)
#define KEYMOD_OPENAPPLE SDL_KMOD_LGUI
#define KEYMOD_CLOSEDAPPLE SDL_KMOD_RGUI
#define KEY_RESET SDLK_PAUSE
#elif defined(windows)
#define KEYMOD_OPENAPPLE SDL_KMOD_LGUI
#define KEYMOD_CLOSEDAPPLE SDL_KMOD_RGUI
#define KEY_RESET SDLK_F10
#endif

#define KEYMOD_REMOVE (~(SDL_KMOD_ALT | SDL_KMOD_GUI))
