#pragma once

#ifdef __APPLE__
/* #define KEYMOD_OPENAPPLE SDL_KMOD_LALT
#define KEYMOD_CLOSEDAPPLE SDL_KMOD_RALT */
#define KEYMOD_OPENAPPLE (SDL_KMOD_LGUI|SDL_KMOD_RGUI)
#define KEYMOD_CLOSEDAPPLE (SDL_KMOD_LALT|SDL_KMOD_RALT)
#define KEY_OPTION_L SDL_SCANCODE_LALT
#define KEY_OPTION_R SDL_SCANCODE_RALT
#define KEY_COMMAND_L SDL_SCANCODE_LGUI
#define KEY_COMMAND_R SDL_SCANCODE_RGUI
#define KEY_RESET SDLK_F10
#elif defined(linux)
#define KEYMOD_OPENAPPLE (SDL_KMOD_LALT|SDL_KMOD_RALT)
#define KEYMOD_CLOSEDAPPLE (SDL_KMOD_LGUI|SDL_KMOD_RGUI)
#define KEY_OPTION_L SDL_SCANCODE_LGUI
#define KEY_OPTION_R SDL_SCANCODE_RGUI
#define KEY_COMMAND_L SDL_SCANCODE_LALT
#define KEY_COMMAND_R SDL_SCANCODE_RALT
#define KEY_RESET SDLK_PAUSE
#elif defined(windows)
#define KEYMOD_OPENAPPLE SDL_KMOD_LGUI
#define KEYMOD_CLOSEDAPPLE SDL_KMOD_RGUI
#define KEY_OPTION_L SDL_SCANCODE_LGUI
#define KEY_OPTION_R SDL_SCANCODE_RGUI
#define KEY_COMMAND_L SDL_SCANCODE_LALT
#define KEY_COMMAND_R SDL_SCANCODE_RALT
#define KEY_RESET SDLK_F10
#endif

#define KEYMOD_REMOVE (~(SDL_KMOD_ALT | SDL_KMOD_GUI))
