#!/usr/bin/env bash
# Deploy the Emscripten build to gssquared.net/live.
#
# The whole /live directory is generated: this script rsyncs the build products
# plus a .htaccess straight to the web server, bypassing the gssquared-web git
# repo (11 MB of wasm per build has no business in a marketing site's history).
# A fresh server clone therefore has no /live until this runs again.
#
# Usage: scripts/deploy-web.sh [--skip-build] [--dry-run]
#
# Overrides:
#   GS2_WEB_HOST       ssh destination            (default bazyar@gssquared.net)
#   GS2_WEB_PATH       remote directory           (default /var/www/gssquared.net/public/live)
#   GS2_WEB_BUILD_DIR  local emscripten build dir (default build-web)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

REMOTE_HOST="${GS2_WEB_HOST:-bazyar@gssquared.net}"
REMOTE_PATH="${GS2_WEB_PATH:-/var/www/gssquared.net/public/live}"
BUILD_DIR="${GS2_WEB_BUILD_DIR:-build-web}"

SKIP_BUILD=0
DRY_RUN=0
for arg in "$@"; do
    case "$arg" in
        --skip-build) SKIP_BUILD=1 ;;
        --dry-run)    DRY_RUN=1 ;;
        -h|--help)
            sed -n '2,14p' "$0"
            exit 0
            ;;
        *)
            echo "Unknown option: $arg" >&2
            echo "Usage: $0 [--skip-build] [--dry-run]" >&2
            exit 1
            ;;
    esac
done

if [[ ! -f "$BUILD_DIR/CMakeCache.txt" ]]; then
    echo "No Emscripten build in '$BUILD_DIR'. Configure it first:" >&2
    echo "  emcmake cmake -S . -B $BUILD_DIR -DCMAKE_BUILD_TYPE=Release -DGS2_WEB_DEBUG=OFF" >&2
    exit 1
fi

if [[ "$SKIP_BUILD" -eq 0 ]]; then
    echo "Building $BUILD_DIR..."
    cmake --build "$BUILD_DIR" --target GSSquared --parallel
fi

# GS2_WEB_DEBUG (on by default) links -g2 -sASSERTIONS=1, which bloats the wasm
# every visitor downloads.
if grep -q '^GS2_WEB_DEBUG:BOOL=ON' "$BUILD_DIR/CMakeCache.txt"; then
    echo "Warning: $BUILD_DIR was configured with GS2_WEB_DEBUG=ON (symbols + assertions)." >&2
    echo "         For a leaner deploy: cmake -S . -B $BUILD_DIR -DGS2_WEB_DEBUG=OFF" >&2
fi

for f in GSSquared.html GSSquared.js GSSquared.wasm GSSquared.data; do
    if [[ ! -f "$BUILD_DIR/$f" ]]; then
        echo "Missing build product: $BUILD_DIR/$f" >&2
        exit 1
    fi
done

STAGE="$(mktemp -d "${TMPDIR:-/tmp}/gs2-live.XXXXXX")"
trap 'rm -rf "$STAGE"' EXIT

# The generated page ships as index.php so it can grow PHP includes later; it is
# plain HTML today (no short tags), so PHP just passes it through.
cp "$BUILD_DIR/GSSquared.html" "$STAGE/index.php"
cp "$BUILD_DIR/GSSquared.js" "$BUILD_DIR/GSSquared.wasm" "$BUILD_DIR/GSSquared.data" "$STAGE/"
cp "$ROOT/assets/web/live.htaccess" "$STAGE/.htaccess"

# Set the modes here rather than with rsync --chmod, which macOS's rsync
# (openrsync) does not implement. rsync -a then preserves them.
chmod 755 "$STAGE"
chmod 644 "$STAGE"/* "$STAGE/.htaccess"

echo
echo "Staged $(du -sh "$STAGE" | cut -f1) for ${REMOTE_HOST}:${REMOTE_PATH}"
ls -lA "$STAGE"
echo

RSYNC_OPTS=(-avz --delete)
if [[ "$DRY_RUN" -eq 1 ]]; then
    RSYNC_OPTS+=(--dry-run)
    echo "(dry run)"
fi

# --delete is safe: everything under /live is generated by this script.
rsync "${RSYNC_OPTS[@]}" "$STAGE/" "${REMOTE_HOST}:${REMOTE_PATH}/"

echo
if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "Dry run complete; nothing was uploaded."
else
    echo "Deployed: https://gssquared.net/live/"
fi
