#pragma once

typedef enum {
    MODULE_DISPLAY = 0,
    MODULE_KEYBOARD,
    MODULE_SPEAKER,
    MODULE_GAMECONTROLLER,
    MODULE_DISKII,
    MODULE_MEMEXP,
    MODULE_THUNDERCLOCK,
    MODULE_PRODOS_CLOCK,
    MODULE_PARALLEL,
    MODULE_VIDEX,
    //MODULE_MB,
    MODULE_IIEMEMORY,
    MODULE_CASSETTE,
    MODULE_KEYGLOO,
    MODULE_IIGSMEMORY,
    MODULE_NUM_MODULES
} module_id_t;
