"""GSSquared external debug protocol client."""

from .client import BpInfo, Client, HelloInfo, StatusInfo, StoppedEvent, TraceWindow
from .errors import ProtocolError
from .keys import (
    KMOD_CTRL,
    KMOD_LCTRL,
    KMOD_LSHIFT,
    KMOD_NONE,
    KMOD_SHIFT,
    SCANCODE_F12,
    SCANCODE_LCTRL,
    SCANCODE_LSHIFT,
    SCANCODE_RETURN,
    SCANCODE_SPACE,
)
from .types import (
    BP_ACCESS_NONE,
    BP_ACCESS_R,
    BP_ACCESS_RW,
    BP_ACCESS_W,
    BP_CLEAR,
    BP_CLEAR_ALL,
    BP_ENABLE,
    BP_FLAG_DATA_MATCH,
    BP_FLAG_ENABLED,
    BP_FLAG_TEMPORARY,
    BP_KIND_DATA,
    BP_KIND_EXEC,
    BP_KIND_IO,
    BP_LIST,
    BP_SET,
    CONTINUE,
    ERROR,
    EVENT,
    EVT_RUN_STATE,
    EVT_STOPPED,
    EXEC_NORMAL,
    EXEC_PAUSED,
    EXEC_STEP_INTO,
    GET_STATUS,
    GET_TRACE,
    HELLO,
    KEYEVENT,
    MEM_ADBMICRO,
    MEM_ENSONIQ,
    MEM_MAIN,
    MEM_MAIN_RAW,
    MEM_MEGAII,
    MEM_MEGAII_RAW,
    PAUSE,
    PING,
    QUIT,
    READMEM,
    RESET,
    STATE_GET,
    STEP_INTO,
    DEVICE_ID_ENSONIQ,
    STOP_BP_DATA,
    STOP_BP_EXEC,
    STOP_BP_IO,
    STOP_PAUSE,
    STOP_STEP,
    WRITEMEM,
)

# PlatformId_t / CLI -p N
PLATFORM_APPLE_II = 0
PLATFORM_APPLE_II_PLUS = 1
PLATFORM_APPLE_IIE = 2
PLATFORM_APPLE_IIE_ENHANCED = 3
PLATFORM_APPLE_IIE_65816 = 4
PLATFORM_APPLE_IIGS = 5

__all__ = [
    "Client",
    "HelloInfo",
    "StatusInfo",
    "BpInfo",
    "StoppedEvent",
    "TraceWindow",
    "ProtocolError",
    "HELLO",
    "PING",
    "QUIT",
    "ERROR",
    "EVENT",
    "GET_STATUS",
    "RESET",
    "PAUSE",
    "CONTINUE",
    "STEP_INTO",
    "GET_TRACE",
    "STATE_GET",
    "DEVICE_ID_ENSONIQ",
    "READMEM",
    "WRITEMEM",
    "BP_SET",
    "BP_CLEAR",
    "BP_CLEAR_ALL",
    "BP_ENABLE",
    "BP_LIST",
    "KEYEVENT",
    "MEM_MAIN",
    "MEM_MEGAII",
    "MEM_ENSONIQ",
    "MEM_ADBMICRO",
    "MEM_MAIN_RAW",
    "MEM_MEGAII_RAW",
    "BP_KIND_EXEC",
    "BP_KIND_DATA",
    "BP_KIND_IO",
    "BP_ACCESS_NONE",
    "BP_ACCESS_R",
    "BP_ACCESS_W",
    "BP_ACCESS_RW",
    "BP_FLAG_ENABLED",
    "BP_FLAG_TEMPORARY",
    "BP_FLAG_DATA_MATCH",
    "EVT_STOPPED",
    "EVT_RUN_STATE",
    "STOP_BP_EXEC",
    "STOP_BP_DATA",
    "STOP_BP_IO",
    "STOP_STEP",
    "STOP_PAUSE",
    "EXEC_NORMAL",
    "EXEC_STEP_INTO",
    "EXEC_PAUSED",
    "PLATFORM_APPLE_II",
    "PLATFORM_APPLE_II_PLUS",
    "PLATFORM_APPLE_IIE",
    "PLATFORM_APPLE_IIE_ENHANCED",
    "PLATFORM_APPLE_IIE_65816",
    "PLATFORM_APPLE_IIGS",
    "KMOD_NONE",
    "KMOD_LSHIFT",
    "KMOD_SHIFT",
    "KMOD_LCTRL",
    "KMOD_CTRL",
    "SCANCODE_LCTRL",
    "SCANCODE_LSHIFT",
    "SCANCODE_F12",
    "SCANCODE_RETURN",
    "SCANCODE_SPACE",
]
